all: LibMatrix.class Engine.class LibUtils.class Main.class

Main.class: Main.java
	javac Main.java

Engine.class: Engine.java
	javac Engine.java

LibUtils.class: LibUtils.java
	javac LibUtils.java

LibMatrix.class: LibMatrix.java
	javac LibMatrix.java

clean:
	rm *.class
