all: ProyectUtils.class FalsiMethod.class SecantMethod.class Main.class

Main.class: Main.java
	javac Main.java

ProyectUtils.class: ProyectUtils.java
	javac ProyectUtils.java

FalsiMethod.class: FalsiMethod.java
	javac FalsiMethod.java

SecantMethod.class: SecantMethod.java
	javac SecantMethod.java

clean:
	rm *.class
