all: LibUtils.class Engine.class Main.class

Main.class: Main.java
	javac Main.java

Engine.class: Engine.java
	javac Engine.java

LibUtils.class: LibUtils.java
	javac LibUtils.java

clean:
	rm *.class
